# Generated by Django 5.2.8 on 2025-11-17 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En préparation'), ('DELIVERED', 'Livrée/Retirée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('nom_receveur', models.CharField(max_length=100)),
                ('telephone_receveur', models.CharField(max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.plat')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_commande', to='commandes.commande')),
            ],
        ),
    ]
