# Generated by Django 6.0 on 2025-12-24 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0, help_text='Montant total en FCFA', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la commande (FCFA)')),
                ('nbPlat', models.PositiveIntegerField(default=1, help_text='Quantité commandée', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de plats')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Prêt'), ('delivering', 'En livraison'), ('completed', 'Livrée'), ('failed', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('notes', models.TextField(blank=True, help_text='Instructions spéciales pour cette commande', null=True, verbose_name='Notes/Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Commandée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('plats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='menu.plat')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='commandes_c_created_badc35_idx'), models.Index(fields=['client', '-created_at'], name='commandes_c_client__09cc94_idx'), models.Index(fields=['status', '-created_at'], name='commandes_c_status_76e297_idx')],
            },
        ),
    ]
