# Generated by Django 5.2.8 on 2025-11-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage sur le menu.")),
            ],
            options={
                'verbose_name_plural': 'Catégories de Menu',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Ingrédients et détails du plat.')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('disponible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False, help_text='Est-ce le plat du jour ?')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='menu.categoriemenu')),
            ],
            options={
                'verbose_name_plural': 'Plats',
                'ordering': ['nom'],
            },
        ),
    ]
