# Generated by Django 5.2.8 on 2025-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix',
            field=models.PositiveIntegerField(help_text='Prix en FCFA'),
        ),
    ]
