# Generated by Django 5.2.8 on 2025-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_plat_image_alter_plat_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
