# Generated by Django 5.2.8 on 2025-11-22 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_plat_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0, verbose_name='montant de la commande')),
                ('nbPlat', models.PositiveIntegerField(default=0, verbose_name='nombre de plats commandee')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='status de la commandes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='commander le :')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to=settings.AUTH_USER_MODEL)),
                ('plats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='menu.plat')),
            ],
        ),
    ]
