# Generated by Django 5.2.8 on 2025-11-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_plat_stock_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='customer',
            new_name='client',
        ),
    ]
