# Generated by Django 5.2.8 on 2025-11-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_customer_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
    ]
