# Generated by Django 5.2.8 on 2025-11-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_plat_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
    ]
