# Generated by Django 5.2.8 on 2025-11-21 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('titre_plat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plat dégusté')),
                ('texte', models.TextField(verbose_name='Votre avis')),
                ('note', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (étoiles)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temoignages/', verbose_name='Photo (optionnel)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False, verbose_name='Publier sur le site')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_creation'],
            },
        ),
    ]
