# Generated by Django 5.2.8 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_reservation', models.DateField()),
                ('heure_reservation', models.TimeField()),
                ('nb_personnes', models.IntegerField(default=1)),
                ('note_speciale', models.TextField(blank=True, null=True, verbose_name='Notes spéciales')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=10)),
            ],
            options={
                'ordering': ['date_reservation', 'heure_reservation'],
            },
        ),
    ]
